export const wordList = [
    {id:0, english:"Morning", swedish:"Morgon", options: [ "Dag", "Natt", "Morgon","Middag"]},
    {id:1, english:"Lecture", swedish:"Föreläsning", options: ["Läxa", "Lärare", "Föreläsning","Tenta"]},
    {id:2, english:"Train", swedish:"Tåg", options: ["Tåg", "Tong ", "Bil","Byggnad"]},
    {id:3, english:"Suitcase", swedish:"Resväska", options: [ "Ryggsäck", "Tygkassa","Datorväska", "Resväska"]},
    {id:4, english:"Water", swedish:"Vatten", options: ["Vatten", "Hav", "Kran","Damm"]},
    {id:5, english:"Shoes", swedish:"Skor", options: ["Byxor","Skor", "Tröja","Strumpor"]},
    {id:6, english:"Chair", swedish:"Stol", options: ["Bord", "Stol", "Tallrik","Tavla"]},
    {id:7, english:"Kitchen", swedish:"Kök", options: ["Kök", "Sked", "Gryta","Gaffel"]},
    {id:8, english:"Jacket", swedish:"Jacka", options: ["Kofta", "Jacka", "Tröja","Kavaj"]},
    {id:9, english:"Thanks", swedish:"Tack", options: ["Tack", "Ursäkta", "Snälla","Förlåt"]},
    {id:10, english:"Run", swedish:"Springa", options: ["Gå","Promenera","Klätra","Springa"]},
    {id:11, english:"Food", swedish:"Mat", options: ["Lunch","Frukt","Mat","Grönsaker"]},
    {id:12, english:"Strawberry", swedish:"Jordgubb", options: ["Jordgubb", "Hallon", "Björnbär","Lingon"]},
    {id:13, english:"Sandwich", swedish:"Macka", options: ["Macka", "Rulle", "Lasange","Gryta"]},
    {id:14, english:"Bottle", swedish:"Flaska", options: ["Glas", "Flaska", "Skål","Bricka"]},
    {id:15, english:"Gloves", swedish:"Vantar", options: ["Vantar", "Halsduk", "Mössa","Halsband"]},
    {id:16, english:"Fridge", swedish:"Kylskåp", options: ["Skåp", "Dörr", "Kylskåp","Spis"]},
    {id:17, english:"Window", swedish:"Fönster", options: ["Tak", "Golv", "Vägg","Fönster"]},
    {id:18, english:"Exit", swedish:"Utgång", options: ["Utgång", "Ingång", "Genväg","Väg"]},
    {id:19, english:"Play", swedish:"Leka", options: ["Bygga", "Leka", "Läsa","Måla"]}
]